name: music-website

volumes:
  pgdata:

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin 
      - POSTGRES_DB=music
