spring:
  datasource:
    url: "jdbc:postgresql://172.18.0.2/music"
    username: admin
    password: admin
  jpa: 
    hibernate:
      ddl-auto: none
    generate:
      ddl: false
    properties:
      hibernate:
        generate_statistics: true
        jpa:
          batch_size: 50
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: jpa-export.sql
              create-source: metadata
server:
  error:
    include-stacktrace: never

logging:
  level:
    root: info
    org:
      hibernate:
        stat: debug 
        SQL: debug
