spring:
  datasource:
    url: "jdbc:postgresql://0.0.0.0:5432/music"
    username: admin
    password: admin

    properties:
      hibernate:
        generate_statistics: false
        jpa:
          batch_size: 50
      jakarta:
        persistence:
          schema-generation:
            # scripts:
            #   action: create
            #   create-target: jpa-export.sql
            #   create-source: metadata
            
logging:
  level:
    root: info
    org:
      hibernate:
        stat: debug
        SQL: debug

server:
  error:
    include-stacktrace: never

# app:
#   web:
    # app-uri: http:localhost: 8080
    # public-html: public
    # storage-path: public/storage
    # base-message-source: classpath:messages
